FROM node:21.5.0-slim AS build

WORKDIR /app
COPY ../package.json ../package-lock.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM nginx:alpine AS production

COPY --from=build /app/build /usr/share/nginx/html
COPY production/nginx.prod.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]