version: "3.8"
name: mfl-manager_dev

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mfl-manager
    ports:
      - "27017:27017"
    expose:
      - "27017"

  smtp:
    image: reachfive/fake-smtp-server
    ports:
      - "1025:1025"
      - "1080:1080"

  api:
    image: mfl-manager_api:local
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      DB_HOSTNAME: "mongodb"
      DB_NAME: "mfl-manager"
      DB_USERNAME: "root"
      DB_PASSWORD: "password"
      DB_PORT: "27017"
      DB_DRIVER: "mongodb"
      MAIL_SERVER: "smtp"
      MAIL_STARTTLS: false
      MAIL_SSL_TLS: false
      MAIL_USE_CREDENTIALS: false
      MAIL_VALIDATE_CERTS: false
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - mongodb
      - smtp
    volumes:
      - ../api:/app

  web:
    image: mfl-manager_web:local
    build:
      context: ../web
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../web:/app
      - /app/node_modules
    command: npm start
    environment:
       - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    expose:
      - "3000"

networks:
  default:
    name: mfl-manager